version: "3.8"
services:
    db:
        image: postgis/postgis:13-3.1-alpine
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            timeout: 20s
            retries: 10
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=example
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
    app:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.8-alpine3.10
        working_dir: /var/app
        environment:
            - VERSION=local
            - PYTHONPATH=/var/app
            - PYTHON_ENV=development
            - DATABASE_URL=postgres://root:root@db/example
        volumes:
            - ./src:/var/app
            - packages:/usr/local/lib/python3.8/site-packages/
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
        ports:
            - 8000:8000
        command: sh -c 'apk add --no-cache build-base postgresql-dev && pip install -r requirements.txt && python main.py'

volumes:
    packages:
    data: