name: GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose down -v --rmi="all"
      - run: docker-compose up -d
      - run: while ! $(docker-compose logs --tail="1" app | grep -Eq '.*Application\ startup\ complete.*'); do docker-compose logs --tail="1" app && sleep 5; done;
      - run: docker-compose exec -T app alembic upgrade head
      - run: docker-compose exec -T app pytest -vv -x
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - run: heroku container:login
      - run: heroku container:push --arg=VERSION=${GITHUB_SHA::8} -a melp-mario --recursive web
      - run: heroku container:release -a melp-mario web
